apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizzaorder
  labels:
    app: pizzaorder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizzaorder
  template:
    metadata:
      labels:
        app: pizzaorder
    spec:
      containers:
        - name: pizzaorder
          image: username/pizzaorder:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5